version: '3.8'

networks:
  
  app-tier:
    driver: bridge

services:
  eccomerse:
    build:
      context: .
    restart: unless-stopped
    ports:
      - "8081:8080"
    volumes:
        - ./src:/opt/tbrantleyii/src
        - ./gatsby-browser.js:/opt/tbrantleyii/gatsby-browser.js
        - ./gatsby-config.js:/opt/tbrantleyii/gatsby-config.js
        - ./gatsby-ssr.js:/opt/tbrantleyii/gatsby-ssr.js
        - ./gatsby-node.js:/opt/tbrantleyii/gatsby-node.js
